api:
  root: /api
  pre_middlewares:
    - authenticate
  post_middlewares:
    - errorHandler
  routes:
    users:
      path: /user
      methods:
        GET:
          controller: getUsers
        POST:
          controller: postUsers
          response_code: 201
          body:
            username:
              type: string
            password:
              type: string
            age:
              type: number
          post_middlewares:
           - logRequests
    user:
      path: /user/:id
      query:
        id: Number
      methods:
        GET:
          controller: getUser
        DELETE:
          controller: deleteUser
          pre_middlewares:
            - checkUserPermissions
          post_middlewares:
            - logRequests
