- apiV1:
    root: /api/global/v1
    pre_middlewares:
      - logRequests
    post_middlewares:
      - unknownRoute
    routes:
      - conversations:
          root: /conversations
          pre_middlewares:
            - ensureAuthentification
          routes:
            - conversations:
                path: /
                methods:
                  - GET:
                      controller: getConversations
                  - POST:
                      controller: postConversations
                      response_code: 201
                      pre_middlewares:
                        - ensurePermission
            - conversation:
                path: /:id
                query:
                  - id: ObjectId
                pre_middlewares:
                  - ensurePermission
                methods:
                  - GET:
                      controller: getConversation
                  - PUT:
                      controller: putConversation
                      response_code: 204
                      body:
                        - name:
                            type: String
                        - members:
                            type: [ObjectId]
                        - test:
                            type: Number
                            defaultValue: 5
                  - DELETE:
                      controller: deleteConversation
                      response_code: 205
